### ISSUE TITLE
about “FlightStatisticsDisplayer” file

### ISSUE THREAD

**Issue by ffxh** [DApIA-Project/ADSB-Visualizer#1]
Hello, is there a missing "FlightStatisticsDisplayer" file under the src file? I encountered this error when running this project. What can I do to solve this problem? I would appreciate it if you could answer it

**Comment by melpiro** [comment]
Hello, 
Yes, this file became unnecessary and has been deleted. However, the code has not been correctly updated causing errors. 
I've fixed the problem.
Don't hesitate if you meet other problems.
